### ISSUE TITLE
Getting a memory error while testing Poseidon

### ISSUE THREAD

**Issue by ZerkerEOD** [MythicAgents/poseidon#10]
I am getting a memory error every time I try to run the keylog. Not sure if I am doing something wrong or not.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6b476d]

goroutine 23 [running]:
github.com/MythicAgents/poseidon/Payload_Type/poseidon/agent_code/keylog/keystate.keystateMonitor(0xc00010e0b8)
	/Mythic/agent_code/keylog/keystate/keystate_unix.go:317 +0x12d
created by github.com/MythicAgents/poseidon/Payload_Type/poseidon/agent_code/keylog/keystate.keyLogger
	/Mythic/agent_code/keylog/keystate/keystate_unix.go:413 +0x6e
```

**Comment by xorrior** [comment]
I'll take a look at this. Definitely haven't thoroughly testing keylogging. You see this error on a linux host right? What flavor and kernel version?

**Comment by ZerkerEOD** [comment]
It was a Linux host. It was a while ago but I am pretty sure it was just a DO droplet running a newer ubuntu OS for testing. I am sorry I am not sure of the kernel version though.
